language: cpp
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - python3

script:
  - echo "CXX="$CXX
  - echo "CC="$CC
  - cmake . -DBUILD_PYBULLET=ON -G"Unix Makefiles" #-DCMAKE_CXX_FLAGS=-Werror
  - make -j8
  - ctest -j8 --output-on-failure
  # Build again with double precision
  - cmake . -G "Unix Makefiles" -DUSE_DOUBLE_PRECISION=ON #-DCMAKE_CXX_FLAGS=-Werror
  - make -j8
  - ctest -j8 --output-on-failure
  # Build again with shared libraries
  - cmake . -G "Unix Makefiles" -DBUILD_SHARED_LIBS=ON
  - make -j8
  - ctest -j8 --output-on-failure
  - sudo make install
  - git clean -d -x -ff .
  - cd build3
  - case "$TRAVIS_OS_NAME" in linux) ./premake4_linux64 gmake;; osx) ./premake4_osx gmake;; esac
  - cd gmake
  - make
  - cd ../..
  - S=0; for T in $(ls bin/Test_* | grep -v '^bin/Test_Gwen_OpenGL'); do echo "Running test '$T'..."; "./$T"; SS=$?; echo "Test '$T' exited with status '$SS'"; [ $S -eq 0 ] && S=$SS; done; exit $S
